import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b0f17",
        surface: "#0f131c",
        "surface-container-lowest": "#070a10",
        "surface-container-low": "#121824",
        "surface-container": "#161e2e",
        "surface-container-high": "#1a2234",
        "surface-container-highest": "#222d42",
        "slate-border": "#222e40",
        "slate-border-subtle": "#1b2536",
        primary: {
          DEFAULT: "#f59e0b",
          container: "#f59e0b",
          fixed: "#ffddb8",
          dim: "#ffb95f",
          foreground: "#472a00",
        },
        secondary: {
          DEFAULT: "#4edea3",
          container: "#00a572",
          fixed: "#6ffbbe",
          dim: "#4edea3",
          foreground: "#003824",
        },
        tertiary: {
          DEFAULT: "#a3b18a",
          container: "#a8b68f",
          fixed: "#dae8be",
          dim: "#becca3",
          foreground: "#293417",
        },
        fern: {
          DEFAULT: "#588157",
          subtle: "#223a2a",
        },
        sage: {
          DEFAULT: "#a3b18a",
          dark: "#588157",
        },
        amber: {
          accent: "#f59e0b",
          hover: "#d97706",
          glow: "#fbbf24",
          subtle: "#2b2011",
        },
        "on-surface": "#f8fafc",
        "on-surface-variant": "#dad7cd",
        "on-background": "#dfe2ee",
        outline: "#2b394f",
        "outline-variant": "rgba(43, 57, 79, 0.6)",
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        card: {
          DEFAULT: "#161e2e",
          foreground: "#f8fafc",
        },
        muted: {
          DEFAULT: "#1a2234",
          foreground: "#94a3b8",
        },
        border: "#222e40",
        foreground: "#f8fafc",
        "primary-fg": "#472a00",
        "muted-fg": "#94a3b8",
        ring: "#f59e0b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Hanken Grotesk", "Inter", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "Inter", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-mono-lg": ["JetBrains Mono", "monospace"],
        "label-mono-md": ["JetBrains Mono", "monospace"],
        "label-mono-xs": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;

